version: '2'
services:
  proxy1:
    build: 
      context: host
      args:
        name: nginx
    stdin_open: true
    tty: true
  proxy2:
    build:
      context: host
      args:
        name: nginx
    stdin_open: true
    tty: true
  web1:
    build:
      context: host
      args:
        name: tomcat
    stdin_open: true
    tty: true
  web2:
    build:
      context: host
      args:
        name: tomcat
    stdin_open: true
    tty: true
  db:
    build:
      context: host/mysql
    stdin_open: true
    tty: true
  control-server:
    stdin_open: true
    build: control-server
    links:
      - proxy1
      - proxy2
      - web1
      - web2
      - db
