version: '2'
services:
  proxy1:
    build: host
    stdin_open: true
    tty: true
  proxy2:
    build: host
    stdin_open: true
    tty: true
  web1:
    build: host
    stdin_open: true
    tty: true
  web2:
    build: host
    stdin_open: true
    tty: true
  db:
    build: host
    stdin_open: true
    tty: true
  control-server:
    stdin_open: true
    tty: true
    build: control-server
    links:
      - proxy1
      - proxy2
      - web1
      - web2
      - db
