################################################################
# Web configuration backend
################################################################
[web]
address = ":8090"
################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
watch = true

#[entryPoints]
#  [entryPoints.http]
#  address = ":8070"

[file]
watch=true
[backends]
  [backends.be-backend]
    [backends.be-backend.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.be-backend.servers.server1]
    url = "http://172.17.0.3:80"
    weight = 10
    [backends.be-backend.servers.server2]
    url = "http://172.17.0.4:80"
    weight = 1
[frontends]
  [frontends.fe-frontend]
  backend = "be-backend"
    [frontends.fe-frontend.routes.route1]
    rule = "Host:fe-frontend.docker.local"
