FROM rastasheep/ubuntu-sshd:14.04

ARG name

# Adding User
RUN useradd -m -s /bin/bash $name

USER $name
# Creating home directory
RUN mkdir /home/$name/.ssh

# Setting Key
ADD authorized_keys /home/$name/.ssh/authorized_keys
#RUN chown $name:$name -R /home/$name/.ssh/
#RUN chmod 600 "/home/$name/.ssh/authorized_keys"

#USER root
#RUN chown $name:$name -R /home/$name/.ssh
